# Generated by Django 5.2.2 on 2025-06-22 14:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo_title', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(default=datetime.datetime(2025, 6, 22, 20, 8, 43, 384268))),
            ],
        ),
    ]
