# Generated by Django 5.2.2 on 2025-06-22 14:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='todo_desc',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='todo',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 22, 20, 23, 26, 980373)),
        ),
    ]
