# Generated by Django 5.2.2 on 2025-06-22 18:52

import autoslug.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo_app', '0003_alter_todo_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from=models.CharField(max_length=100), unique=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 23, 0, 22, 5, 585604)),
        ),
    ]
