# Generated by Django 5.2.2 on 2025-06-22 19:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo_app', '0009_alter_todo_created_date_alter_todo_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='slug',
        ),
        migrations.AlterField(
            model_name='todo',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 23, 0, 35, 21, 519710)),
        ),
    ]
