# Generated by Django 5.2.2 on 2025-06-22 19:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo_app', '0015_alter_todo_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 23, 1, 7, 31, 270152)),
        ),
    ]
